export const CONSTANTS = {
  // User
  NICKNAME_MIN_LENGTH: 2,
  NICKNAME_MAX_LENGTH: 20,
  BIO_MAX_LENGTH: 200,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 72,
  EMAIL_MAX_LENGTH: 254,
  AVATAR_MAX_SIZE: 512 * 1024,

  // Post
  POST_CONTENT_MAX_LENGTH: 1000,
  POST_IMAGES_MIN: 1,
  POST_IMAGES_MAX: 9,
  IMAGE_MAX_SIZE: 5 * 1024 * 1024,
  IMAGE_COMPRESSED_TARGET: 200 * 1024,
  IMAGE_ALLOWED_TYPES: ['image/jpeg', 'image/png', 'image/webp'] as const,
  TAG_MAX_LENGTH: 20,
  TAGS_MAX_COUNT: 5,
  LOCATION_MAX_LENGTH: 100,
  RESTAURANT_NAME_MAX_LENGTH: 50,

  // Comment
  COMMENT_MAX_LENGTH: 500,

  // Pagination
  FEED_PAGE_SIZE: 20,
  FEED_PAGE_SIZE_MAX: 50,
  COMMENTS_PAGE_SIZE: 20,

  // Auth
  JWT_EXPIRES_IN_SECONDS: 7 * 24 * 60 * 60, // 7 days
  BCRYPT_ROUNDS: 10,

  // R2
  R2_BUCKET_NAME: 'foodshare-images',
} as const;
